"use strict";

// Rendering stuff
var CLEAR_BOARD_SPRITE = 0;
var WALL_SPRITE = 1;
var START_SPRITE = 2;
var EXIT_SPRITE = 3;
var GLUE_TUBE_SPRITE = 4;
var BAG_PILE_SPRITE = 5;
var GLUE_STAIN_SPRITE = 6;

var BOY_SPRITE = 20;

var BOARD_SPRITE = [];
BOARD_SPRITE[Level.CLEAR] = CLEAR_BOARD_SPRITE;
BOARD_SPRITE[Level.WALL] = WALL_SPRITE;
BOARD_SPRITE[Level.START] = START_SPRITE;
BOARD_SPRITE[Level.EXIT] = EXIT_SPRITE;

var ITEM_SPRITE = [];
ITEM_SPRITE[Item.GLUE_TUBE] = GLUE_TUBE_SPRITE;
ITEM_SPRITE[Item.BAG_PILE] = BAG_PILE_SPRITE;
ITEM_SPRITE[Item.GLUE_STAIN] = GLUE_STAIN_SPRITE;
